In [36]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.layers import Input
from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

In [37]:
#Many-to-One 
#Each time step has one feature

In [38]:
nums = 25

X1 = list()
X2 = list()
X = list()
Y = list()

X1 = [(x+1)*2 for x in range(25)]
X2 = [(x+1)*3 for x in range(25)]
Y = [x1*x2 for x1,x2 in zip(X1,X2)]

print(X1)
print(X2)
print(Y)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75]
[6, 24, 54, 96, 150, 216, 294, 384, 486, 600, 726, 864, 1014, 1176, 1350, 1536, 1734, 1944, 2166, 2400, 2646, 2904, 3174, 3456, 3750]


In [39]:
#The input is a combination of two lists X1 and X2. T
#The output is the product of X1*X2

In [40]:
#Create the input
X = np.column_stack((X1, X2))
print(X)

[[ 2  3]
 [ 4  6]
 [ 6  9]
 [ 8 12]
 [10 15]
 [12 18]
 [14 21]
 [16 24]
 [18 27]
 [20 30]
 [22 33]
 [24 36]
 [26 39]
 [28 42]
 [30 45]
 [32 48]
 [34 51]
 [36 54]
 [38 57]
 [40 60]
 [42 63]
 [44 66]
 [46 69]
 [48 72]
 [50 75]]


In [41]:
# The input set consists of two features per input
# Now convert the input into 3-dimensional shape. 
# Input has 25 samples, where each sample consist of 1 time-step and each time-step consists of 2 features. 

In [42]:
# reshape the input and output
X = array(X).reshape(25, 1, 2)
Y = array(Y).reshape(25, 1, 1)

In [43]:
model = Sequential()
model.add(LSTM(100, activation='relu',return_sequences=True, input_shape=(1, 2)))
model.add(LSTM(25, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_12 (LSTM)               (None, 1, 100)            41200     
_________________________________________________________________
lstm_13 (LSTM)               (None, 25)                12600     
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 26        
Total params: 53,826
Trainable params: 53,826
Non-trainable params: 0
_________________________________________________________________
None


In [44]:
model.fit(X, Y, epochs=100,validation_split=0.2, batch_size=5, verbose =1) 

Epoch 1/100
4/4 [==============================] - 0s 59ms/step - loss: 1300840.2500 - val_loss: 10301355.0000
Epoch 2/100
4/4 [==============================] - 0s 6ms/step - loss: 1300364.7500 - val_loss: 10298705.0000
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 1299934.8750 - val_loss: 10294039.0000
Epoch 4/100
4/4 [==============================] - 0s 6ms/step - loss: 1299045.0000 - val_loss: 10288334.0000
Epoch 5/100
4/4 [==============================] - 0s 5ms/step - loss: 1298174.7500 - val_loss: 10281610.0000
Epoch 6/100
4/4 [==============================] - 0s 6ms/step - loss: 1297040.2500 - val_loss: 10272778.0000
Epoch 7/100
4/4 [==============================] - 0s 5ms/step - loss: 1295348.7500 - val_loss: 10262296.0000
Epoch 8/100
4/4 [==============================] - 0s 6ms/step - loss: 1293292.8750 - val_loss: 10249964.0000
Epoch 9/100
4/4 [==============================] - 0s 5ms/step - loss: 1290892.1250 - val_loss: 10235716.0000
Epoch 10/

Epoch 76/100
4/4 [==============================] - 0s 6ms/step - loss: 32005.2070 - val_loss: 1045671.0000
Epoch 77/100
4/4 [==============================] - 0s 6ms/step - loss: 29262.5586 - val_loss: 997427.8750
Epoch 78/100
4/4 [==============================] - 0s 6ms/step - loss: 23601.4961 - val_loss: 962721.3125
Epoch 79/100
4/4 [==============================] - 0s 6ms/step - loss: 21802.7500 - val_loss: 904217.1875
Epoch 80/100
4/4 [==============================] - 0s 6ms/step - loss: 20519.2559 - val_loss: 873233.0000
Epoch 81/100
4/4 [==============================] - 0s 6ms/step - loss: 19350.2168 - val_loss: 825840.6875
Epoch 82/100
4/4 [==============================] - 0s 6ms/step - loss: 18181.6523 - val_loss: 803233.8750
Epoch 83/100
4/4 [==============================] - 0s 6ms/step - loss: 13524.1279 - val_loss: 773917.3750
Epoch 84/100
4/4 [==============================] - 0s 5ms/step - loss: 12687.5625 - val_loss: 743838.5000
Epoch 85/100
4/4 [==================

In [45]:
# validation_split: Float between 0 and 1. 
# Fraction of the training data to be used as validation data. 
# The model will set apart this fraction of the training data, will not train on it.
# Will evaluate the loss and any model metrics on this data at the end of each epoch. 
# The validation data is selected from the last samples in the x and y data provided, before shuffling.

In [46]:
# Our test data point will have two features i.e. (55,80) the actual output should be 55 x 80 = 4400.

In [47]:
test_input = array([55,80])
test_input = test_input.reshape((1, 1, 2)) # reshaped into 1 sample, 1 time step, 2 feature
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[3025.3318]]


In [48]:
# Many-to-One Sequence Problems with a Single Feature

In [49]:
X = np.array([x+1 for x in range(45)])
print(X)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]


In [50]:
#15 samples, 3 time-steps, and 1 feature.
X = X.reshape(15,3,1) 
print(X)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]

 [[16]
  [17]
  [18]]

 [[19]
  [20]
  [21]]

 [[22]
  [23]
  [24]]

 [[25]
  [26]
  [27]]

 [[28]
  [29]
  [30]]

 [[31]
  [32]
  [33]]

 [[34]
  [35]
  [36]]

 [[37]
  [38]
  [39]]

 [[40]
  [41]
  [42]]

 [[43]
  [44]
  [45]]]


In [51]:
# each element in the output will be equal to
# the sum of the values in the time-steps in the corresponding input sample

In [52]:
Y = list()
for x in X:
    Y.append(x.sum())

Y = np.array(Y)
print(Y)

[  6  15  24  33  42  51  60  69  78  87  96 105 114 123 132]


In [53]:
model = Sequential()
model.add(LSTM(100, activation='relu',return_sequences=True, input_shape=(3, 1))) #3 time step, 1 feature
model.add(LSTM(25, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
print(model.summary())

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_14 (LSTM)               (None, 3, 100)            40800     
_________________________________________________________________
lstm_15 (LSTM)               (None, 25)                12600     
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 26        
Total params: 53,426
Trainable params: 53,426
Non-trainable params: 0
_________________________________________________________________
None


In [54]:
history = model.fit(X, Y, epochs=100, validation_split=0.2, verbose=1)

Epoch 1/100
1/1 [==============================] - 0s 233ms/step - loss: 4048.3457 - val_loss: 15112.6318
Epoch 2/100
1/1 [==============================] - 0s 20ms/step - loss: 4037.0244 - val_loss: 15058.7998
Epoch 3/100
1/1 [==============================] - 0s 22ms/step - loss: 4024.2410 - val_loss: 14997.8438
Epoch 4/100
1/1 [==============================] - 0s 20ms/step - loss: 4010.3254 - val_loss: 14932.3281
Epoch 5/100
1/1 [==============================] - 0s 20ms/step - loss: 3995.2874 - val_loss: 14861.2031
Epoch 6/100
1/1 [==============================] - 0s 28ms/step - loss: 3978.7656 - val_loss: 14782.7500
Epoch 7/100
1/1 [==============================] - 0s 20ms/step - loss: 3960.5361 - val_loss: 14697.0068
Epoch 8/100
1/1 [==============================] - 0s 20ms/step - loss: 3940.6047 - val_loss: 14603.7451
Epoch 9/100
1/1 [==============================] - 0s 21ms/step - loss: 3918.6963 - val_loss: 14502.1904
Epoch 10/100
1/1 [==============================] - 0s

1/1 [==============================] - 0s 18ms/step - loss: 28.5729 - val_loss: 87.0521
Epoch 81/100
1/1 [==============================] - 0s 20ms/step - loss: 26.7440 - val_loss: 73.6896
Epoch 82/100
1/1 [==============================] - 0s 18ms/step - loss: 24.7259 - val_loss: 59.7844
Epoch 83/100
1/1 [==============================] - 0s 20ms/step - loss: 22.7242 - val_loss: 46.4494
Epoch 84/100
1/1 [==============================] - 0s 18ms/step - loss: 20.9046 - val_loss: 34.5162
Epoch 85/100
1/1 [==============================] - 0s 20ms/step - loss: 19.3707 - val_loss: 24.4883
Epoch 86/100
1/1 [==============================] - 0s 18ms/step - loss: 18.1564 - val_loss: 16.5545
Epoch 87/100
1/1 [==============================] - 0s 20ms/step - loss: 17.2343 - val_loss: 10.6450
Epoch 88/100
1/1 [==============================] - 0s 17ms/step - loss: 16.5295 - val_loss: 6.5102
Epoch 89/100
1/1 [==============================] - 0s 21ms/step - loss: 15.9424 - val_loss: 3.8048
Epoch

In [55]:
test_input = array([50,51,52])
test_input = test_input.reshape((1, 3, 1)) #sample size=1, time step =3, feature =1
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[152.94255]]
