In [3]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten, LSTM
from keras.layers import GlobalMaxPooling1D
from keras.models import Model
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.layers import Input
from keras.layers.merge import Concatenate
from keras.layers import Bidirectional

import pandas as pd
import numpy as np
import re

import matplotlib.pyplot as plt

In [4]:
X = np.array([x+1 for x in range(45)])
print(X)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45]


In [5]:
#15 samples, 3 time-steps, and 1 feature.
X = X.reshape(15,3,1) 
print(X)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]

 [[13]
  [14]
  [15]]

 [[16]
  [17]
  [18]]

 [[19]
  [20]
  [21]]

 [[22]
  [23]
  [24]]

 [[25]
  [26]
  [27]]

 [[28]
  [29]
  [30]]

 [[31]
  [32]
  [33]]

 [[34]
  [35]
  [36]]

 [[37]
  [38]
  [39]]

 [[40]
  [41]
  [42]]

 [[43]
  [44]
  [45]]]


each element in the output will be equal to the sum of the values in the time-steps in the corresponding input sample

In [6]:
Y = list()
for x in X:
    Y.append(x.sum())

Y = np.array(Y)
print(Y)

[  6  15  24  33  42  51  60  69  78  87  96 105 114 123 132]


In [ ]:
#Solution via Bidirectional LSTM
#learns from the input sequence from both forward and backward directions.
#The final sequence interpretation is the concatenation of both forward and backward learning passes. 

In [7]:
from keras.layers import Bidirectional

model = Sequential()
model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(3, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [8]:
history = model.fit(X, Y, epochs=1000, validation_split=0.2, verbose=1)
test_output = model.predict(test_input, verbose=0)
print(test_output)

Epoch 1/1000
1/1 [==============================] - 0s 258ms/step - loss: 4091.3816 - val_loss: 15212.1045
Epoch 2/1000
1/1 [==============================] - 0s 19ms/step - loss: 4040.7605 - val_loss: 15006.6680
Epoch 3/1000
1/1 [==============================] - 0s 18ms/step - loss: 3990.2500 - val_loss: 14801.0576
Epoch 4/1000
1/1 [==============================] - 0s 20ms/step - loss: 3939.7771 - val_loss: 14595.1455
Epoch 5/1000
1/1 [==============================] - 0s 19ms/step - loss: 3889.2913 - val_loss: 14388.7422
Epoch 6/1000
1/1 [==============================] - 0s 20ms/step - loss: 3838.7117 - val_loss: 14181.6514
Epoch 7/1000
1/1 [==============================] - 0s 18ms/step - loss: 3787.9426 - val_loss: 13973.6514
Epoch 8/1000
1/1 [==============================] - 0s 20ms/step - loss: 3736.8789 - val_loss: 13764.4844
Epoch 9/1000
1/1 [==============================] - 0s 19ms/step - loss: 3685.3860 - val_loss: 13553.8516
Epoch 10/1000
1/1 [==========================

1/1 [==============================] - 0s 22ms/step - loss: 26.5240 - val_loss: 5.4895
Epoch 80/1000
1/1 [==============================] - 0s 21ms/step - loss: 24.5418 - val_loss: 3.2020
Epoch 81/1000
1/1 [==============================] - 0s 19ms/step - loss: 22.4497 - val_loss: 1.3737
Epoch 82/1000
1/1 [==============================] - 0s 22ms/step - loss: 20.3784 - val_loss: 0.2659
Epoch 83/1000
1/1 [==============================] - 0s 19ms/step - loss: 18.4403 - val_loss: 0.0523
Epoch 84/1000
1/1 [==============================] - 0s 22ms/step - loss: 16.7242 - val_loss: 0.8080
Epoch 85/1000
1/1 [==============================] - 0s 20ms/step - loss: 15.2905 - val_loss: 2.5086
Epoch 86/1000
1/1 [==============================] - 0s 20ms/step - loss: 14.1712 - val_loss: 5.0393
Epoch 87/1000
1/1 [==============================] - 0s 19ms/step - loss: 13.3702 - val_loss: 8.2113
Epoch 88/1000
1/1 [==============================] - 0s 20ms/step - loss: 12.8659 - val_loss: 11.7824
Epo

1/1 [==============================] - 0s 18ms/step - loss: 1.0473 - val_loss: 0.6560
Epoch 161/1000
1/1 [==============================] - 0s 20ms/step - loss: 0.9929 - val_loss: 0.6013
Epoch 162/1000
1/1 [==============================] - 0s 22ms/step - loss: 0.9393 - val_loss: 0.5538
Epoch 163/1000
1/1 [==============================] - 0s 19ms/step - loss: 0.8858 - val_loss: 0.5123
Epoch 164/1000
1/1 [==============================] - 0s 20ms/step - loss: 0.8328 - val_loss: 0.4715
Epoch 165/1000
1/1 [==============================] - 0s 19ms/step - loss: 0.7816 - val_loss: 0.4193
Epoch 166/1000
1/1 [==============================] - 0s 20ms/step - loss: 0.7315 - val_loss: 0.3720
Epoch 167/1000
1/1 [==============================] - 0s 19ms/step - loss: 0.6826 - val_loss: 0.3314
Epoch 168/1000
1/1 [==============================] - 0s 20ms/step - loss: 0.6342 - val_loss: 0.2965
Epoch 169/1000
1/1 [==============================] - 0s 19ms/step - loss: 0.5853 - val_loss: 0.2646
Epoch

1/1 [==============================] - 0s 20ms/step - loss: 7.4597e-04 - val_loss: 0.0016
Epoch 241/1000
1/1 [==============================] - 0s 19ms/step - loss: 7.3421e-04 - val_loss: 0.0016
Epoch 242/1000
1/1 [==============================] - 0s 17ms/step - loss: 7.2289e-04 - val_loss: 0.0016
Epoch 243/1000
1/1 [==============================] - 0s 20ms/step - loss: 7.1123e-04 - val_loss: 0.0014
Epoch 244/1000
1/1 [==============================] - 0s 18ms/step - loss: 6.9978e-04 - val_loss: 0.0013
Epoch 245/1000
1/1 [==============================] - 0s 22ms/step - loss: 6.8966e-04 - val_loss: 0.0012
Epoch 246/1000
1/1 [==============================] - 0s 19ms/step - loss: 6.7998e-04 - val_loss: 0.0012
Epoch 247/1000
1/1 [==============================] - 0s 21ms/step - loss: 6.7170e-04 - val_loss: 0.0012
Epoch 248/1000
1/1 [==============================] - 0s 19ms/step - loss: 6.6481e-04 - val_loss: 0.0011
Epoch 249/1000
1/1 [==============================] - 0s 20ms/step - l

Epoch 316/1000
1/1 [==============================] - 0s 20ms/step - loss: 5.1921e-04 - val_loss: 8.8052e-04
Epoch 317/1000
1/1 [==============================] - 0s 18ms/step - loss: 5.1769e-04 - val_loss: 8.8689e-04
Epoch 318/1000
1/1 [==============================] - 0s 22ms/step - loss: 5.1629e-04 - val_loss: 8.9183e-04
Epoch 319/1000
1/1 [==============================] - 0s 18ms/step - loss: 5.1484e-04 - val_loss: 8.9306e-04
Epoch 320/1000
1/1 [==============================] - 0s 20ms/step - loss: 5.1345e-04 - val_loss: 8.9276e-04
Epoch 321/1000
1/1 [==============================] - 0s 19ms/step - loss: 5.1205e-04 - val_loss: 8.9522e-04
Epoch 322/1000
1/1 [==============================] - 0s 21ms/step - loss: 5.1061e-04 - val_loss: 9.0286e-04
Epoch 323/1000
1/1 [==============================] - 0s 20ms/step - loss: 5.0923e-04 - val_loss: 9.0953e-04
Epoch 324/1000
1/1 [==============================] - 0s 17ms/step - loss: 5.0785e-04 - val_loss: 9.1098e-04
Epoch 325/1000
1/1 

1/1 [==============================] - 0s 23ms/step - loss: 4.2352e-04 - val_loss: 9.1222e-04
Epoch 392/1000
1/1 [==============================] - 0s 19ms/step - loss: 4.2233e-04 - val_loss: 9.1005e-04
Epoch 393/1000
1/1 [==============================] - 0s 20ms/step - loss: 4.2116e-04 - val_loss: 9.1054e-04
Epoch 394/1000
1/1 [==============================] - 0s 19ms/step - loss: 4.1996e-04 - val_loss: 9.0938e-04
Epoch 395/1000
1/1 [==============================] - 0s 20ms/step - loss: 4.1879e-04 - val_loss: 9.0668e-04
Epoch 396/1000
1/1 [==============================] - 0s 19ms/step - loss: 4.1763e-04 - val_loss: 9.0365e-04
Epoch 397/1000
1/1 [==============================] - 0s 20ms/step - loss: 4.1644e-04 - val_loss: 9.0198e-04
Epoch 398/1000
1/1 [==============================] - 0s 19ms/step - loss: 4.1526e-04 - val_loss: 9.0091e-04
Epoch 399/1000
1/1 [==============================] - 0s 18ms/step - loss: 4.1410e-04 - val_loss: 8.9973e-04
Epoch 400/1000
1/1 [==============

1/1 [==============================] - 0s 20ms/step - loss: 3.4158e-04 - val_loss: 7.6704e-04
Epoch 467/1000
1/1 [==============================] - 0s 19ms/step - loss: 3.4051e-04 - val_loss: 7.6370e-04
Epoch 468/1000
1/1 [==============================] - 0s 19ms/step - loss: 3.3966e-04 - val_loss: 7.5917e-04
Epoch 469/1000
1/1 [==============================] - 0s 18ms/step - loss: 3.3869e-04 - val_loss: 7.5851e-04
Epoch 470/1000
1/1 [==============================] - 0s 20ms/step - loss: 3.3771e-04 - val_loss: 7.5775e-04
Epoch 471/1000
1/1 [==============================] - 0s 22ms/step - loss: 3.3660e-04 - val_loss: 7.5500e-04
Epoch 472/1000
1/1 [==============================] - 0s 19ms/step - loss: 3.3564e-04 - val_loss: 7.5134e-04
Epoch 473/1000
1/1 [==============================] - 0s 18ms/step - loss: 3.3467e-04 - val_loss: 7.5001e-04
Epoch 474/1000
1/1 [==============================] - 0s 20ms/step - loss: 3.3371e-04 - val_loss: 7.4814e-04
Epoch 475/1000
1/1 [==============

1/1 [==============================] - 0s 18ms/step - loss: 2.7250e-04 - val_loss: 5.8899e-04
Epoch 542/1000
1/1 [==============================] - 0s 19ms/step - loss: 2.7171e-04 - val_loss: 5.8670e-04
Epoch 543/1000
1/1 [==============================] - 0s 18ms/step - loss: 2.7079e-04 - val_loss: 5.8632e-04
Epoch 544/1000
1/1 [==============================] - 0s 18ms/step - loss: 2.6999e-04 - val_loss: 5.8524e-04
Epoch 545/1000
1/1 [==============================] - 0s 20ms/step - loss: 2.6915e-04 - val_loss: 5.8078e-04
Epoch 546/1000
1/1 [==============================] - 0s 18ms/step - loss: 2.6833e-04 - val_loss: 5.7722e-04
Epoch 547/1000
1/1 [==============================] - 0s 20ms/step - loss: 2.6745e-04 - val_loss: 5.7697e-04
Epoch 548/1000
1/1 [==============================] - 0s 19ms/step - loss: 2.6662e-04 - val_loss: 5.7506e-04
Epoch 549/1000
1/1 [==============================] - 0s 21ms/step - loss: 2.6577e-04 - val_loss: 5.7202e-04
Epoch 550/1000
1/1 [==============

1/1 [==============================] - 0s 34ms/step - loss: 2.1425e-04 - val_loss: 4.1718e-04
Epoch 617/1000
1/1 [==============================] - 0s 21ms/step - loss: 2.1349e-04 - val_loss: 4.1561e-04
Epoch 618/1000
1/1 [==============================] - 0s 19ms/step - loss: 2.1276e-04 - val_loss: 4.1319e-04
Epoch 619/1000
1/1 [==============================] - 0s 18ms/step - loss: 2.1217e-04 - val_loss: 4.1027e-04
Epoch 620/1000
1/1 [==============================] - 0s 18ms/step - loss: 2.1145e-04 - val_loss: 4.0871e-04
Epoch 621/1000
1/1 [==============================] - 0s 21ms/step - loss: 2.1066e-04 - val_loss: 4.0721e-04
Epoch 622/1000
1/1 [==============================] - 0s 18ms/step - loss: 2.1004e-04 - val_loss: 4.0446e-04
Epoch 623/1000
1/1 [==============================] - 0s 19ms/step - loss: 2.0935e-04 - val_loss: 4.0142e-04
Epoch 624/1000
1/1 [==============================] - 0s 21ms/step - loss: 2.0866e-04 - val_loss: 3.9992e-04
Epoch 625/1000
1/1 [==============

1/1 [==============================] - 0s 21ms/step - loss: 1.6597e-04 - val_loss: 2.6403e-04
Epoch 692/1000
1/1 [==============================] - 0s 19ms/step - loss: 1.6536e-04 - val_loss: 2.6085e-04
Epoch 693/1000
1/1 [==============================] - 0s 20ms/step - loss: 1.6482e-04 - val_loss: 2.5796e-04
Epoch 694/1000
1/1 [==============================] - 0s 19ms/step - loss: 1.6428e-04 - val_loss: 2.5763e-04
Epoch 695/1000
1/1 [==============================] - 0s 20ms/step - loss: 1.6365e-04 - val_loss: 2.5649e-04
Epoch 696/1000
1/1 [==============================] - 0s 18ms/step - loss: 1.6310e-04 - val_loss: 2.5283e-04
Epoch 697/1000
1/1 [==============================] - 0s 19ms/step - loss: 1.6256e-04 - val_loss: 2.5127e-04
Epoch 698/1000
1/1 [==============================] - 0s 20ms/step - loss: 1.6195e-04 - val_loss: 2.5152e-04
Epoch 699/1000
1/1 [==============================] - 0s 22ms/step - loss: 1.6134e-04 - val_loss: 2.4837e-04
Epoch 700/1000
1/1 [==============

1/1 [==============================] - 0s 19ms/step - loss: 1.2684e-04 - val_loss: 1.4009e-04
Epoch 767/1000
1/1 [==============================] - 0s 20ms/step - loss: 1.2640e-04 - val_loss: 1.3878e-04
Epoch 768/1000
1/1 [==============================] - 0s 18ms/step - loss: 1.2594e-04 - val_loss: 1.3744e-04
Epoch 769/1000
1/1 [==============================] - 0s 19ms/step - loss: 1.2543e-04 - val_loss: 1.3588e-04
Epoch 770/1000
1/1 [==============================] - 0s 20ms/step - loss: 1.2500e-04 - val_loss: 1.3489e-04
Epoch 771/1000
1/1 [==============================] - 0s 19ms/step - loss: 1.2455e-04 - val_loss: 1.3297e-04
Epoch 772/1000
1/1 [==============================] - 0s 21ms/step - loss: 1.2403e-04 - val_loss: 1.3135e-04
Epoch 773/1000
1/1 [==============================] - 0s 17ms/step - loss: 1.2358e-04 - val_loss: 1.3061e-04
Epoch 774/1000
1/1 [==============================] - 0s 21ms/step - loss: 1.2310e-04 - val_loss: 1.3003e-04
Epoch 775/1000
1/1 [==============

1/1 [==============================] - 0s 19ms/step - loss: 9.5599e-05 - val_loss: 5.7405e-05
Epoch 842/1000
1/1 [==============================] - 0s 21ms/step - loss: 9.5247e-05 - val_loss: 5.6462e-05
Epoch 843/1000
1/1 [==============================] - 0s 20ms/step - loss: 9.4883e-05 - val_loss: 5.6278e-05
Epoch 844/1000
1/1 [==============================] - 0s 18ms/step - loss: 9.4581e-05 - val_loss: 5.4868e-05
Epoch 845/1000
1/1 [==============================] - 0s 21ms/step - loss: 9.4127e-05 - val_loss: 5.4259e-05
Epoch 846/1000
1/1 [==============================] - 0s 18ms/step - loss: 9.3757e-05 - val_loss: 5.3606e-05
Epoch 847/1000
1/1 [==============================] - 0s 22ms/step - loss: 9.3366e-05 - val_loss: 5.2880e-05
Epoch 848/1000
1/1 [==============================] - 0s 20ms/step - loss: 9.3029e-05 - val_loss: 5.2036e-05
Epoch 849/1000
1/1 [==============================] - 0s 18ms/step - loss: 9.2705e-05 - val_loss: 5.1568e-05
Epoch 850/1000
1/1 [==============

1/1 [==============================] - 0s 18ms/step - loss: 7.1241e-05 - val_loss: 1.9115e-05
Epoch 917/1000
1/1 [==============================] - 0s 17ms/step - loss: 7.0915e-05 - val_loss: 1.8507e-05
Epoch 918/1000
1/1 [==============================] - 0s 20ms/step - loss: 7.0646e-05 - val_loss: 1.8420e-05
Epoch 919/1000
1/1 [==============================] - 0s 18ms/step - loss: 7.0354e-05 - val_loss: 1.8283e-05
Epoch 920/1000
1/1 [==============================] - 0s 19ms/step - loss: 7.0087e-05 - val_loss: 1.7906e-05
Epoch 921/1000
1/1 [==============================] - 0s 20ms/step - loss: 6.9818e-05 - val_loss: 1.7729e-05
Epoch 922/1000
1/1 [==============================] - 0s 17ms/step - loss: 6.9536e-05 - val_loss: 1.7740e-05
Epoch 923/1000
1/1 [==============================] - 0s 18ms/step - loss: 6.9256e-05 - val_loss: 1.7453e-05
Epoch 924/1000
1/1 [==============================] - 0s 20ms/step - loss: 6.8967e-05 - val_loss: 1.7218e-05
Epoch 925/1000
1/1 [==============

1/1 [==============================] - 0s 20ms/step - loss: 5.2413e-05 - val_loss: 2.2047e-05
Epoch 992/1000
1/1 [==============================] - 0s 19ms/step - loss: 5.2191e-05 - val_loss: 2.2194e-05
Epoch 993/1000
1/1 [==============================] - 0s 21ms/step - loss: 5.2003e-05 - val_loss: 2.2648e-05
Epoch 994/1000
1/1 [==============================] - 0s 21ms/step - loss: 5.1764e-05 - val_loss: 2.3082e-05
Epoch 995/1000
1/1 [==============================] - 0s 18ms/step - loss: 5.1574e-05 - val_loss: 2.3215e-05
Epoch 996/1000
1/1 [==============================] - 0s 17ms/step - loss: 5.1380e-05 - val_loss: 2.3609e-05
Epoch 997/1000
1/1 [==============================] - 0s 20ms/step - loss: 5.1160e-05 - val_loss: 2.4165e-05
Epoch 998/1000
1/1 [==============================] - 0s 21ms/step - loss: 5.0897e-05 - val_loss: 2.4292e-05
Epoch 999/1000
1/1 [==============================] - 0s 19ms/step - loss: 5.0728e-05 - val_loss: 2.4611e-05
Epoch 1000/1000
1/1 [=============

NameError: name 'test_input' is not defined

In [9]:
test_input = array([50,51,52])
test_input = test_input.reshape((1, 3, 1))
test_output = model.predict(test_input, verbose=0)
print(test_output)

[[153.03903]]
